[tool.poetry]
authors = ["Jeff Hutchison <jeff@j3ff.io>"]
description = "Stryke Force Website"
license = "MIT"
name = "stryke_force_website"
packages = [
  {include = "website"},
]
readme = "README.md"
version = "4.0.0"

[tool.poetry.group.main.dependencies]
Django = {extras = ["argon2"], version = "^4.2"}
python = "^3.10"
whitenoise = {extras = ["brotli"], version = "^6.1.0"}
wagtail = "^5.1.2"
factory-boy = "^3.2.1"
gunicorn = "^21.2"
tba-api-v3client = "^3.8.0"
hiredis = "^2.1.0"
sentry-sdk = "^1.13.0"
opencv-python-headless = "^4.8"
psycopg  = {extras = ["binary", "pool"], version = "^3.1"}
redis = "^5.0"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
rich = "^13.0.0"
django-debug-toolbar = "^4.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
