[tool.poetry]
authors = ["Jeff Hutchison <jeff@j3ff.io>"]
description = "Stryke Force Website"
license = "MIT"
name = "stryke_force_website"
packages = [
  {include = "website"},
]
readme = "README.md"
version = "4.1.8"

[tool.poetry.group.main.dependencies]
Django = {extras = ["argon2"], version = "^5.0"}
python = "^3.10"
whitenoise = {extras = ["brotli"], version = "^6.6.0"}
wagtail = "^6.1"
factory-boy = "^3.2.1"
gunicorn = "^22.0.0"
tba-api-v3client = "^3.8.0"
hiredis = "^2.1.0"
sentry-sdk = "^1.40.0"
opencv-python = "^4.0"
psycopg  = {extras = ["binary", "pool"], version = "^3.1"}
redis = "^5.0"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
rich = "^13.7.1"
django-debug-toolbar = "^4.2"
ipython = "^8.22.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
