[[events]]
name = "Indiana Robotics Invitational"
date = 2019-07-12T00:00:00Z
venue = "Lawrence North High School"
street = "7802 Hague Rd"
city = "Indianapolis"
state = "IN"
zip = "46256"

[[events]]
name = "West Michigan Robotics Invitational"
date = 2019-10-19T00:00:00Z
venue = "Zeeland East High School"
street = "3333 96th Ave."
city = "Zeeland"
state = "MI"
zip = "49464"
