[[events]]
name = "Constantine FTC Qualifier"
date = 2018-11-07T00:00:00Z
venue = "Constantine High School"
street = "1 Falcon Dr."
city = "Constantine"
state = "MI"
zip = "49042"

[[events]]
name = "Coloma FTC Qualifier"
date = 2018-12-01T00:00:00Z
venue = "Coloma High School"
street = "500 W. St. Joseph St."
city = "Coloma"
state = "MI"
zip = "49038"

[[events]]
name = "St. Joseph FRC District"
date = 2019-03-07T00:00:00Z
venue = "St. Joseph High School"
street = "2521 Stadium Dr."
city = "St. Joseph"
state = "MI"
zip = "49085"

[[events]]
name = "East Kentwood FRC District"
date = 2019-03-28T00:00:00Z
venue = "East Kentwood High School"
street = "6230 Kalamazoo Avenue SE"
city = "Kentwood"
state = "MI"
zip = "49508"