[[students]]
  id = "92dbdaf3-6ee1-4b13-91dd-809518aa639c"
  name = "Audrey Rabick"
  displayName = "Audrey R."
  photo = "./about/team/2018/audrey_r.jpg"
  grade = 12
  school = "Comstock"
  quote = "My two favorite historic inventions are duct tape and whiteboards."

[[students]]
  id = "9854d066-d828-4615-a896-70af83402527"
  name = "Cade Peterman"
  displayName = "Cade P."
  photo = "./about/team/2018/cade_p.jpg"
  grade = 12
  school = "Loy Norrix"
  quote = "I'm not a quotable person. Yay robots?"

[[students]]
  id = "7269aeb0-9b2d-40c9-a89c-05f987af38f0"
  name = "Greg Redlon"
  displayName = "Greg R."
  photo = "./about/team/2018/greg_r.jpg"
  grade = 12
  school = "Portage Central"
  quote = ""

[[students]]
  id = "cd42e451-541e-40c1-863c-012366cdb13c"
  name = "Hunter McGillivray"
  displayName = "Hunter M."
  photo = "./about/team/2018/hunter_m.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "The single most rewarding experience in the world is creating an experience for some of your dearest friends and watching them tear it apart..."

[[students]]
  id = "efc8b85f-5f32-40f4-8a7e-7d647c4660ed"
  name = "Jack Bruinwood"
  displayName = "Jack B."
  photo = "./about/team/2018/jack_b.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Two robots drove into a bar, the third one had me as a driver."

[[students]]
  id = "1e87d112-da7f-450a-9330-5cdb05707ba8"
  name = "Matt Clark"
  displayName = "Matt C."
  photo = "./about/team/2018/matt_c.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "If it ain't broke don't fix it. If it is-ZIP TIES!"

[[students]]
  id = "ef2bd4f1-2913-4cd7-bc83-dc0b47282d68"
  name = "Roberts Kalnins"
  displayName = "Roberts K."
  photo = "./about/team/2018/roberts_k.jpg"
  grade = 12
  school = "Portage Northern"
  quote = ""

[[students]]
  id = "d3e6f637-6202-42a4-9281-ddcce7504598"
  name = "Ross Malackowski"
  displayName = "Ross M."
  photo = "./about/team/2018/ross_m.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Stryke Force helps me fly!"

[[students]]
  id = "45d1eb1c-423c-4ba2-ba44-9e5a861e0c56"
  name = "Sam Breuer"
  displayName = "Sam B."
  photo = "./about/team/2018/sam_b.jpg"
  grade = 12
  school = "Portage Central"
  quote = "Did somebody say scouting, I'm so glad you asked!"

[[students]]
  id = "00afa4e2-b0b3-4eaa-921c-916415d04b4e"
  name = "Sierra Staunton"
  displayName = "Sierra S."
  photo = "./about/team/2018/sierra_s.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "Leaders aren't those who love to win, but those who hate to lose."

[[students]]
  id = "95626d16-e217-4d5b-aa84-fa0dd13c5f1e"
  name = "Anna Puca"
  displayName = "Anna P."
  photo = "./about/team/2018/anne_p.jpg"
  grade = 11
  school = "Loy Norrix"
  quote = "Don't get mono two weeks before the World Championship Robotics Competition."

[[students]]
  id = "4cb6bd97-77d1-41bc-81dc-e681ecdc304a"
  name = "Brianna Kohl"
  displayName = "Brianna K."
  photo = "./about/team/2018/brianna_k.jpg"
  grade = 11
  school = "Mattawan"
  quote = "When life throws a swerve at you, make lemonade."

[[students]]
  id = "9f602c90-8b13-4ae4-a2fd-aa60bb54588e"
  name = "Ethan Lee"
  displayName = "Ethan L."
  photo = "./about/team/2018/ethan_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Don't call it a dream. Call it a plan."

[[students]]
  id = "af755052-eb95-4ed8-82d7-ed142769ea91"
  name = "Kris Ouvry"
  displayName = "Kris O."
  photo = "./about/team/2018/kris_o.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Stryke Force Yellow: a man-made marvel seen from space."

[[students]]
  id = "814cd035-c4a4-47da-acb9-3fc9f5ee28d6"
  name = "Lilian Gates"
  displayName = "Lilian G."
  photo = "./about/team/2018/lilian_g.jpg"
  grade = 11
  school = "Portage Central"
  quote = "It's always a software problem."

[[students]]
  id = "f73de192-565c-4dd8-b087-0694cedcd6dd"
  name = "Ranya Liu"
  displayName = "Ranya L."
  photo = "./about/team/2018/ranya_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Came for the food, stayed for the robot."

[[students]]
  id = "91dd7f72-06e1-4023-acd4-5b7ce13baec9"
  name = "Alex Zajac"
  displayName = "Alex Z."
  photo = "./about/team/2018/alex_z.jpg"
  grade = 10
  school = "Loy Norrix"
  quote = "Feels good to get your hands dirty."

[[students]]
  id = "e7c8cea9-147d-453c-9dcf-f2c9424327fd"
  name = "David Herr"
  displayName = "David H."
  photo = "./about/team/2018/david_h.jpg"
  grade = 10
  school = "Portage Central"
  quote = ""

[[students]]
  id = "53f397b9-60d6-4c20-a44d-8733b9ecb196"
  name = "Jacob Woessner"
  displayName = "Jacob W."
  photo = "./about/team/2018/jacob_w.jpg"
  grade = 10
  school = "Portage Central"
  quote = ""

[[students]]
  id = "b756a123-d901-48d1-969e-e72042f417d0"
  name = "Kjerstin Lindbloom"
  displayName = "Kjerstin L."
  photo = "./about/team/2018/kjerstin_l.jpg"
  grade = 10
  school = "Mattawan"
  quote = ""

[[students]]
  id = "d881549c-1a3a-4f4e-89d1-7103d2dfc370"
  name = "Sam Rabick"
  displayName = "Sam R."
  photo = "./about/team/2018/sam_r.jpg"
  grade = 10
  school = "Comstock"
  quote = "If we accepted the sky as the limit, we would never have put a man on the moon."

[[students]]
  id = "abf78098-af46-4209-ab0c-495b87f88632"
  name = "Cole Sherwood"
  displayName = "Cole S."
  photo = "./about/team/2018/cole_s.jpg"
  grade = 9
  school = "Portage Central"
  quote = ""

[[students]]
  id = "cf023166-54c7-4bcb-acbb-db2b9e9af96b"
  name = "Siddhart Tiwari"
  displayName = "Siddhart T."
  photo = "./about/team/2018/siddhart_t.jpg"
  grade = 9
  school = "Portage Central"
  quote = ""

[[students]]
  id = "a0bc778e-803f-4e7d-88dd-ee6a49be193c"
  name = "Zach McDougal"
  displayName = "Zach M."
  photo = "./about/team/2018/zach_m.jpg"
  grade = 9
  school = ""
  quote = ""

