[[students]]
  id = "15eba106-96e2-4301-a873-26880f246e6e"
  name = "Audrey Rabick"
  displayName = "Audrey R."
  photo = "./about/team/2018/audrey_r.jpg"
  grade = 12
  school = "Comstock"
  quote = "My two favorite historic inventions are duct tape and whiteboards."

[[students]]
  id = "3e7f1bdc-447a-47f9-a86f-f7e8d3189453"
  name = "Cade Peterman"
  displayName = "Cade P."
  photo = "./about/team/2018/cade_p.jpg"
  grade = 12
  school = "Loy Norrix"
  quote = "I'm not a quotable person. Yay robots?"

[[students]]
  id = "72edc6b2-766d-4071-8afc-8ed8bbef355f"
  name = "Greg Redlon"
  displayName = "Greg R."
  photo = "./about/team/2018/greg_r.jpg"
  grade = 12
  school = "Portage Central"
  quote = ""

[[students]]
  id = "416c6563-7559-4564-a6f5-feca3b8be1f1"
  name = "Hunter McGillivray"
  displayName = "Hunter M."
  photo = "./about/team/2018/hunter_m.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "The single most rewarding experience in the world is creating an experience for some of your dearest friends and watching them tear it apart and exploit every weakness in your mechanics."

[[students]]
  id = "6ad74d96-d83d-4bca-bee4-7d884e3e4f36"
  name = "Jack Bruinwood"
  displayName = "Jack B."
  photo = "./about/team/2018/jack_b.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Two robots drove into a bar, the third one had me as a driver."

[[students]]
  id = "2186807d-a5e8-4ae7-bfbc-8b63f5eefc8d"
  name = "Matt Clark"
  displayName = "Matt C."
  photo = "./about/team/2018/matt_c.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "If it ain't broke don't fix it. If it is ZIP TIES!"

[[students]]
  id = "5f0e9ab5-938d-462c-8932-4aa70686d5bd"
  name = "Ross Malackowski"
  displayName = "Ross M."
  photo = "./about/team/2018/ross_m.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Strykeforce helps me fly!"

[[students]]
  id = "8e122b95-1b90-41ef-b1a5-ea002710e84d"
  name = "Sierra Staunton"
  displayName = "Sierra S."
  photo = "./about/team/2018/sierra_s.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "Leaders aren't those who love to win, but those who hate to lose."

[[students]]
  id = "2da8e77c-cd11-4249-9617-accc5655fbb8"
  name = "Anna Puca"
  displayName = "Anna P."
  photo = "./about/team/2018/anne_p.jpg"
  grade = 11
  school = "Loy Norrix"
  quote = "Don't get mono two weeks before the World Championship Robotics Competition."

[[students]]
  id = "df069fba-cdb5-453d-a4a6-f422b81e6e06"
  name = "Brianna Kohl"
  displayName = "Brianna K."
  photo = "./about/team/2018/brianna_k.jpg"
  grade = 11
  school = "Mattawan"
  quote = "When life throws a swerve at you, make lemonade."

[[students]]
  id = "c9baec7f-f771-4463-a619-b33cdafa0f77"
  name = "Ethan Lee"
  displayName = "Ethan L."
  photo = "./about/team/2018/ethan_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Don't call it a dream. Call it a plan."

[[students]]
  id = "98626c0b-99dd-4805-a0ff-9f0853736a79"
  name = "Kris Ouvry"
  displayName = "Kris O."
  photo = "./about/team/2018/kris_o.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Stryke Force Yellow- a man-made marvel seen from space."

[[students]]
  id = "b0205831-57a5-4792-aba8-31b11144476f"
  name = "Lilian Gates"
  displayName = "Lilian G."
  photo = "./about/team/2018/lilian_g.jpg"
  grade = 11
  school = "Portage Central"
  quote = "It's always a software problem."

[[students]]
  id = "b8f92539-5e67-452f-9d02-72cbc9d933df"
  name = "Ranya Liu"
  displayName = "Ranya L."
  photo = "./about/team/2018/ranya_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Came for the food stayed for the robot."

[[students]]
  id = "ffab054e-fae8-48a0-9fd3-9b46177ac8f8"
  name = "Alex Zajac"
  displayName = "Alex Z."
  photo = "./about/team/2018/alex_z.jpg"
  grade = 10
  school = "Loy Norrix"
  quote = "Feels good to get your hands dirty."

[[students]]
  id = "87a7c3e7-54b7-4c7e-b10e-fdb163c45c1c"
  name = "David Herr"
  displayName = "David H."
  photo = "./about/team/2018/david_h.jpg"
  grade = 10
  school = "Portage Central"
  quote = ""

[[students]]
  id = "804b4d86-c004-4a79-b7ed-0881702bb25f"
  name = "Kjerstin Lindbloom"
  displayName = "Kjerstin L."
  photo = "./about/team/2018/kjerstin_l.jpg"
  grade = 10
  school = "Mattawan"
  quote = ""

[[students]]
  id = "cd97f5d5-debc-40b9-a4b7-b42a32b2aae4"
  name = "Sam Rabick"
  displayName = "Sam R."
  photo = "./about/team/2018/sam_r.jpg"
  grade = 10
  school = "Comstock"
  quote = "If we accepted the sky as the limit, we would never have put a man on the moon."

