[[students]]
  id = "c205e3e2-e569-42cc-82a1-34bc29342169"
  name = "Audrey Rabick"
  displayName = "Audrey R."
  photo = "./about/team/2018/audrey_r.jpg"
  grade = 12
  school = "Comstock"
  quote = "My two favorite historic inventions are duct tape and whiteboards."

[[students]]
  id = "14b9ddde-b0d3-4590-ae86-c73f920e01fa"
  name = "Cade Peterman"
  displayName = "Cade P."
  photo = "./about/team/2018/cade_p.jpg"
  grade = 12
  school = "Loy Norrix"
  quote = "I'm not a quotable person. Yay robots?"

[[students]]
  id = "7fb2295a-7876-40b0-82ab-4f63b2295fb2"
  name = "Carter Briggs"
  displayName = "Carter B."
  photo = "./about/team/2018/carter_b.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "Engineering is solving problems you didn't know you had in ways you don't understant."

[[students]]
  id = "f35af411-1a60-44dd-970e-959c19f18d37"
  name = "Greg Redlon"
  displayName = "Greg R."
  photo = "./about/team/2018/greg_r.jpg"
  grade = 12
  school = "Portage Central"
  quote = "There wouldn’t be good times without the tough times."

[[students]]
  id = "5fea54be-9464-427e-add3-05397aa8f442"
  name = "Hunter McGillivray"
  displayName = "Hunter M."
  photo = "./about/team/2018/hunter_m.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "The single most rewarding experience in the world is creating an experience for some of your dearest friends and watching them tear it apart..."

[[students]]
  id = "ea0b108c-b3b7-4696-b112-1b5d64e221cb"
  name = "Jack Bruinwood"
  displayName = "Jack B."
  photo = "./about/team/2018/jack_b.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Two robots drove into a bar, the third one had me as a driver."

[[students]]
  id = "e3c3b1d2-9c64-45a0-a04d-48cfc6ef4eb8"
  name = "Matt Clark"
  displayName = "Matt C."
  photo = "./about/team/2018/matt_c.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "If it ain't broke don't fix it. If it is-ZIP TIES!"

[[students]]
  id = "0f56346d-e212-4ea6-a53e-cb2428fdb567"
  name = "Roberts Kalnins"
  displayName = "Roberts K."
  photo = "./about/team/2018/roberts_k.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "I'm trilingual — I speak English, Latvian, and Java."

[[students]]
  id = "d999892e-eb9d-4ff8-8ca7-0b46c3f2d1e2"
  name = "Ross Malackowski"
  displayName = "Ross M."
  photo = "./about/team/2018/ross_m.jpg"
  grade = 12
  school = "Homeschool"
  quote = "Stryke Force helps me fly!"

[[students]]
  id = "ccb78b41-b739-4638-a243-25216affdbb5"
  name = "Sam Breuer"
  displayName = "Sam B."
  photo = "./about/team/2018/sam_b.jpg"
  grade = 12
  school = "Portage Central"
  quote = "Did somebody say scouting, I'm so glad you asked!"

[[students]]
  id = "d0808f41-96cf-4b6f-8da5-112685358fd5"
  name = "Sierra Staunton"
  displayName = "Sierra S."
  photo = "./about/team/2018/sierra_s.jpg"
  grade = 12
  school = "Portage Northern"
  quote = "Leaders aren't those who love to win, but those who hate to lose."

[[students]]
  id = "e611f31f-848a-420e-a24d-86f9feb4291a"
  name = "Anna Puca"
  displayName = "Anna P."
  photo = "./about/team/2018/anne_p.jpg"
  grade = 11
  school = "Loy Norrix"
  quote = "Don't get mono two weeks before the World Championship Robotics Competition."

[[students]]
  id = "ccb33f01-8e35-475b-a07a-9b66ac9f7249"
  name = "Brianna Kohl"
  displayName = "Brianna K."
  photo = "./about/team/2018/brianna_k.jpg"
  grade = 11
  school = "Mattawan"
  quote = "When life throws a swerve at you, make lemonade."

[[students]]
  id = "7e245294-fa22-4e00-a091-fc8115cf0bcc"
  name = "Ethan Lee"
  displayName = "Ethan L."
  photo = "./about/team/2018/ethan_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Don't call it a dream. Call it a plan."

[[students]]
  id = "fe55db40-0d08-4e9c-94bc-e6aab5045bd0"
  name = "Kris Ouvry"
  displayName = "Kris O."
  photo = "./about/team/2018/kris_o.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Stryke Force Yellow: a man-made marvel seen from space."

[[students]]
  id = "b452dd22-c120-40bf-a95e-23fec56a7475"
  name = "Lilian Gates"
  displayName = "Lilian G."
  photo = "./about/team/2018/lilian_g.jpg"
  grade = 11
  school = "Portage Central"
  quote = "It's always a software problem."

[[students]]
  id = "91a80022-105c-430b-88aa-55e259b83ab0"
  name = "Ranya Liu"
  displayName = "Ranya L."
  photo = "./about/team/2018/ranya_l.jpg"
  grade = 11
  school = "Portage Central"
  quote = "Came for the food, stayed for the robot."

[[students]]
  id = "00d83548-8ba0-4080-9b60-51088c1312ba"
  name = "Alex Zajac"
  displayName = "Alex Z."
  photo = "./about/team/2018/alex_z.jpg"
  grade = 10
  school = "Loy Norrix"
  quote = "Feels good to get your hands dirty."

[[students]]
  id = "59263375-188e-4e85-af42-d153588f206e"
  name = "David Herr"
  displayName = "David H."
  photo = "./about/team/2018/david_h.jpg"
  grade = 10
  school = "Portage Central"
  quote = ""

[[students]]
  id = "c1ad2576-7cb6-44c7-aa36-5fb41de551dc"
  name = "Jacob Woessner"
  displayName = "Jacob W."
  photo = "./about/team/2018/jacob_w.jpg"
  grade = 10
  school = "Portage Central"
  quote = ""

[[students]]
  id = "3c410950-b7c5-47a9-85b1-f0f3ad2ecf87"
  name = "Jager Doorn"
  displayName = "Jager D."
  photo = "./about/team/2018/jager_d.jpg"
  grade = 10
  school = "Homeschool"
  quote = ""

[[students]]
  id = "37ab5c7f-8067-4336-9156-471904360808"
  name = "Kjerstin Lindbloom"
  displayName = "Kjerstin L."
  photo = "./about/team/2018/kjerstin_l.jpg"
  grade = 10
  school = "Mattawan"
  quote = "Uniqueness is what I strive for, awkwardness is what I have."

[[students]]
  id = "2c990779-cab6-4644-baa5-a36740d59e6e"
  name = "Sam Rabick"
  displayName = "Sam R."
  photo = "./about/team/2018/sam_r.jpg"
  grade = 10
  school = "Comstock"
  quote = "If we accepted the sky as the limit, we would never have put a man on the moon."

[[students]]
  id = "86d620fb-d349-46e1-9747-0d9298b4cd3b"
  name = "Cassie Nash"
  displayName = "Cassie N."
  photo = "./about/team/2018/cassie_n.jpg"
  grade = 9
  school = "Kalamazoo Central"
  quote = ""

[[students]]
  id = "e95891e0-528f-46eb-8c4d-b46809775645"
  name = "Cole Sherwood"
  displayName = "Cole S."
  photo = "./about/team/2018/cole_s.jpg"
  grade = 9
  school = "Portage Central"
  quote = ""

[[students]]
  id = "7c811c37-19e1-412c-8633-c7c797e9a80b"
  name = "Siddhart Tiwari"
  displayName = "Siddhart T."
  photo = "./about/team/2018/siddhart_t.jpg"
  grade = 9
  school = "Portage Central"
  quote = ""

[[students]]
  id = "fa0a36d1-13b6-4e47-bbdd-63fe4a935cbe"
  name = "Zach McDougal"
  displayName = "Zach M."
  photo = "./about/team/2018/zach_m.jpg"
  grade = 9
  school = "Portage Central"
  quote = ""

