baseURL = "https://www.strykeforce.org/"
languageCode = "en-us"
languageLang = "en"
title = "Stryke Force"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# sectionPagesMenu = "main"

[[menu.Main]]
    	identifier = "about"
    	name       = "About Us"
    	url        = "/about/"
    	weight     = 10

[[menu.Main]]
	identifier = "blog"
	name       = "Blog"
	url        = "/blog/"
	weight     = 20


[params]
  GithubID = "strykeforce"
  TwitterID = "2767StrykeForce"
  FacebookID = "2767strykeforce"
  InstagramID = "2767strykeforce"
  Name = "Stryke Force 2767"
  About = "This is the Stryke Force Web Site. Stryke Force is a community FIRST robotics team based in Kalamazoo, Michigan. We are FRC 2767, FTC 7228 and FTC 8553."
  ProfilePicture = "strykeforce.jpg"
  GoogleAnalytics = "UA-108186367-3"
