# Generated by Django 4.1.5 on 2023-01-19 13:40
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_joinformpage_joinformfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joinformpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="JoinFormField",
        ),
        migrations.DeleteModel(
            name="JoinFormPage",
        ),
    ]
