# Generated by Django 4.1.5 on 2023-01-20 11:15
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("members", "0003_remove_joinformpage_page_ptr_delete_joinformfield_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Text to describe the page",
                        max_length=1000,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
