# Generated by Django 4.1.5 on 2023-01-20 11:35
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_studentindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="blurb",
            field=models.TextField(blank=True),
        ),
    ]
