# Generated by Django 4.1.5 on 2023-01-21 15:47
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_studentindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("STUDENT_LEADER", "Student Leader"),
                    ("MENTOR", "Mentor"),
                    ("OTHER", "Other"),
                ],
                default="STUDENT",
                max_length=50,
            ),
        ),
    ]
