# Generated by Django 4.1.5 on 2023-01-24 15:24
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_member_member_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentindexpage",
            old_name="body",
            new_name="introduction",
        ),
    ]
