#!/usr/bin/env bash

# script/update: Update my_awesome_project  to run for its current checkout.

source "$(dirname "$0")/.config"

script/bootstrap || exit 1

if [ -n "$USE_TAILWIND_CSS" ]; then
    _message "==> Updating Tailwind CSS…"
    npx postcss "$APPS_DIR/static/css/base.css" -o "$APPS_DIR/static/css/main.css"
    NODE_ENV=production npx postcss "$APPS_DIR/static/css/base.css" -o "$APPS_DIR/static/css/main.min.css"
fi

MISSING_CSS="$APPS_DIR/static/css/missing.min.css"
if [ -n "$USE_MISSING_CSS" ]; then
    _message "==> Updating Missing CSS…"
    if [ ! -f "$MISSING_CSS" ]; then
        curl https://the.missing.style/v1.0.1/missing.min.css --output "$MISSING_CSS"
    fi
fi

if [ -n "$USE_PICO_CSS" ]; then
    _message "==> Updating Pico CSS…"
    cp node_modules/@picocss/pico/css/pico.min.css "$APPS_DIR/static/css/"
fi

if [ -n "$USE_HTMX" ]; then
    _message "==> Updating HTMX…"
    cp node_modules/htmx.org/dist/htmx.min.js "$APPS_DIR/static/js/"
    cp node_modules/htmx.org/dist/ext/class-tools.js "$APPS_DIR/static/js/"
fi

if [ -n "$USE_HYPERSCRIPT" ]; then
    _message "==> Updating _Hyperscript…"
    cp node_modules/hyperscript.org/dist/_hyperscript.min.js "$APPS_DIR/static/js/"
fi
