# Generated by Django 4.1.4 on 2022-12-28 22:47
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0006_teampage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamPage",
            new_name="AboutPage",
        ),
    ]
