# Generated by Django 4.1.4 on 2022-12-29 21:40
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_contentpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPage",
        ),
    ]
