# Generated by Django 4.1.5 on 2023-01-12 11:59
from __future__ import annotations

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0011_rename_partnerspage_sponsorspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("website", models.URLField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("PLATINUM", "Platinum"),
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("BRONZE", "Bronze"),
                        ],
                        default="BRONZE",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "sponsor",
                "verbose_name_plural": "sponsors",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddIndex(
            model_name="sponsor",
            index=models.Index(
                fields=["level", "name"], name="home_sponso_level_ee6564_idx"
            ),
        ),
    ]
