# Generated by Django 4.1.5 on 2023-01-26 13:08
from __future__ import annotations

import django.db.models.deletion
import wagtail.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0015_rename_intro_contentpage_introduction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPageIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
