# Generated by Django 4.1.5 on 2023-01-31 11:59
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0016_contentpageindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_page_1",
            field=models.ForeignKey(
                blank=True,
                help_text="First featured page for the homepage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured page 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_page_2",
            field=models.ForeignKey(
                blank=True,
                help_text="Second featured page for the homepage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured page 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_page_3",
            field=models.ForeignKey(
                blank=True,
                help_text="Third featured page for the homepage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured page 3",
            ),
        ),
    ]
