# Generated by Django 4.1.5 on 2023-01-05 20:25
from __future__ import annotations

import django.db.models.deletion
import wagtail.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Text to describe the page",
                        max_length=1000,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("tba_url", models.URLField(blank=True, verbose_name="TBA URL")),
                ("event_url", models.URLField(blank=True, verbose_name="Event URL")),
                ("venue", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=10)),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            bases=("wagtailcore.page",),
        ),
        migrations.AddIndex(
            model_name="eventpage",
            index=models.Index(fields=["date_start"], name="events_even_date_st_4bebc3_idx"),
        ),
    ]
