# Generated by Django 4.1.5 on 2023-01-24 15:42
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpage",
            name="introduction",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
