# Generated by Django 5.1.5 on 2025-01-16 18:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventindexpage_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="division_keys",
        ),
        migrations.RemoveField(
            model_name="event",
            name="first_event_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="playoff_type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="playoff_type_string",
        ),
        migrations.AddField(
            model_name="event",
            name="awards",
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="edited_on",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(default="default", editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="district",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.CharField(
                blank=True,
                help_text="Short and unique (i.e. misjo, openhouse, etc.)",
                max_length=25,
                verbose_name="Event Code",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type_string",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="first_event_code",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="gmaps_place_id",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="gmaps_url",
            field=models.URLField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=25,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="lat",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="lng",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Familiar location name (i.e. Fieldhouse Arena) or street address.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="If this is blank, it is recommended to copy an earlier version of this event and edit as neccessary.",
                max_length=255,
                verbose_name="Event Name",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="parent_event_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="postal_code",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="state_prov",
            field=models.CharField(
                blank=True,
                default="MI",
                max_length=255,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="webcasts",
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="year",
            field=models.IntegerField(default=2025, help_text="Year of event"),
        ),
    ]
