# Generated by Django 5.1.5 on 2025-01-24 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_event_division_keys_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
    ]
