# Generated by Django 5.1.5 on 2025-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type_string",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
