# Generated by Django 6.0 on 2026-01-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_event_type_string_alter_event_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="year",
            field=models.IntegerField(default=2026, help_text="Year of event"),
        ),
    ]
