# Generated by Django 4.1.5 on 2023-01-17 13:48
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpage",
            index=models.Index(fields=["-date"], name="blog_blogpa_date_7f56a0_idx"),
        ),
    ]
