# Generated by Django 4.1.4 on 2022-12-28 22:28
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpagegalleryimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="intro",
            new_name="body",
        ),
    ]
