# Generated by Django 4.1.4 on 2022-12-30 13:23
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("blog", "0004_rename_intro_blogindexpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
