# Generated by Django 4.1.4 on 2022-12-30 13:28
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpage_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
