# Generated by Django 4.1.4 on 2022-12-30 23:26
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("blog", "0006_delete_blogpagegalleryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="introduction",
            field=models.TextField(default="edit me", help_text="Text to describe the page"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Landscape mode only; horizontal width greater than 1200 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
