# Generated by Django 4.1.4 on 2022-12-31 00:04
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_blogpage_intro_blogpage_introduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="Text to describe the page",
                max_length=1000,
            ),
        ),
    ]
