name: "Build strykeforce.org"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v15
        with:
          name: strykeforce
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
